#!/usr/bin/env bash
# Run on Casper (NCAR) to configure or start the ucar-uxarray-yac Globus Compute endpoint.
set -euo pipefail

# ---------------------------------------------------------------------------
# USER CONFIG — change these to match your account before running
# ---------------------------------------------------------------------------
USERNAME="${NCAR_USERNAME:-$USER}"   # override with NCAR_USERNAME if it differs
# ---------------------------------------------------------------------------

ENDPOINT_NAME="${ENDPOINT_NAME:-ucar-uxarray-yac}"
CONDA_ENV="/glade/work/$USERNAME/conda-envs/uxarray_dev"
# Override to test a freshly built YAC without editing this file:
#   YAC_VERSION=3.18 ucar_endpoint.sh restart
# Bump the default only once that build is verified on the endpoint. 3.20.2 was
# verified on Casper: the uxarray helper resolved to the 3.20.2 .so and a real
# HEALPix remap ran. worker_init sources activate-yac.sh from this prefix, so
# `restart` is what picks the change up.
YAC_VERSION="${YAC_VERSION:-3.20.2}"
YAC_PREFIX="$HOME/opt/yac-$YAC_VERSION"
YAC_ACTIVATE="$YAC_PREFIX/activate-yac.sh"
TMUX_SESSION="uxarray-endpoint"
# NOTE: the MCP server repo does NOT need to be cloned on UCAR. Remote
# functions are serialised via AllCodeStrategies and run with only uxarray
# + numpy + matplotlib installed in the conda env. Never add uxarray_mcp
# to PYTHONPATH on the worker — it causes pydantic version conflicts.

usage() {
  cat <<'EOF'
Usage (run on a Casper login node):
  ucar_endpoint.sh configure    Write endpoint config files (once per install)
  ucar_endpoint.sh start        Load env + start endpoint in tmux
  ucar_endpoint.sh restart      Stop running endpoint, then start fresh
  ucar_endpoint.sh status       Show endpoint list

Environment overrides:
  ENDPOINT_NAME   Globus Compute endpoint profile name (default: ucar-uxarray-yac)
EOF
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_load_modules() {
  if ! command -v module &>/dev/null 2>&1; then
    for _init in \
      /usr/share/lmod/lmod/init/bash \
      /etc/profile.d/lmod.sh \
      /glade/u/apps/opt/lmod/init/bash; do
      [[ -f "$_init" ]] && source "$_init" && break
    done
  fi

  module purge
  module load ncarenv/24.12
  module load gcc/12.4.0
  module load openmpi/5.0.6
  module load conda
}

_activate_env() {
  # shellcheck disable=SC1091
  source "$(conda info --base)/etc/profile.d/conda.sh"
  conda activate "$CONDA_ENV"
  _ensure_yac_activate
  # shellcheck disable=SC1091
  source "$YAC_ACTIVATE"
}

# Only the hand-built 3.18 prefix ships an activate-yac.sh; prefixes built by
# scripts/hpc_build_yac.py do not. Synthesize one from the prefix so
# YAC_VERSION can point at a fresh build with no manual step, and so
# worker_init -- which sources this same file -- keeps working.
_ensure_yac_activate() {
  [[ -f "$YAC_ACTIVATE" ]] && return 0
  if [[ ! -d "$YAC_PREFIX/lib" ]]; then
    echo "ERROR: no YAC install at $YAC_PREFIX (YAC_VERSION=$YAC_VERSION)." >&2
    echo "  Build it first, or unset YAC_VERSION to use the default." >&2
    return 1
  fi
  local pyver
  pyver="$(python -c 'import sys;print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
  cat > "$YAC_ACTIVATE" <<EOF
# Generated by ucar_endpoint.sh for YAC $YAC_VERSION -- safe to delete.
export PYTHONPATH="$YAC_PREFIX/lib/python$pyver/site-packages:\${PYTHONPATH:-}"
export LD_LIBRARY_PATH="$YAC_PREFIX/lib:\${LD_LIBRARY_PATH:-}"
EOF
  echo "  wrote $YAC_ACTIVATE (YAC $YAC_VERSION, python $pyver)"
}

_check_yac() {
  if python -c 'import yac; import yac.core; print("  YAC OK:", yac.core.__file__)' 2>/dev/null; then
    return 0
  fi
  echo "WARNING: yac.core not importable — YAC remapping will be unavailable."
  echo "  Run: find $YAC_PREFIX \\( -name 'core*.so' -o -name '_yac*.so' \\) -print"
  echo "  If missing, rebuild YAC with: --enable-python-bindings PYTHON=\$(which python)"
  echo "  Continuing — all non-YAC tools will work normally."
}

# ---------------------------------------------------------------------------
# configure: write Globus Compute template + environment files
# ---------------------------------------------------------------------------

_configure() {
  local ep_dir="$HOME/.globus_compute/$ENDPOINT_NAME"

  if [[ ! -d "$ep_dir" ]]; then
    echo "Creating endpoint profile: $ENDPOINT_NAME"
    globus-compute-endpoint configure "$ENDPOINT_NAME"
  fi

  cat > "$ep_dir/user_config_template.yaml.j2" <<EOF
endpoint_setup: ""

engine:
  type: GlobusComputeEngine
  max_workers_per_node: 1
  provider:
    type: LocalProvider
    min_blocks: 0
    max_blocks: 1
    init_blocks: 1
    worker_init: |
      unset PYTHONPATH
      source "\$(conda info --base)/etc/profile.d/conda.sh"
      conda activate $CONDA_ENV
      source $YAC_ACTIVATE

idle_heartbeats_soft: 10
idle_heartbeats_hard: 5760
EOF

  cat > "$ep_dir/user_environment.yaml" <<EOF
PATH: "$CONDA_ENV/bin:/usr/bin:/bin"
EOF

  echo "Wrote:"
  echo "  $ep_dir/user_config_template.yaml.j2"
  echo "  $ep_dir/user_environment.yaml"
  echo
  echo "Next: ucar_endpoint.sh start"
}

# ---------------------------------------------------------------------------
# _do_start: the real work, called inside tmux
# ---------------------------------------------------------------------------

_do_start() {
  echo "==> Loading modules..."
  _load_modules
  echo "==> Activating conda env: $CONDA_ENV"
  _activate_env
  echo "==> Checking YAC..."
  _check_yac
  # `globus-compute-endpoint start` against a profile that is already Running
  # takes the live endpoint down rather than no-opping, and reports success
  # while doing it. Refuse, and name the verb that actually works. Must come
  # after _activate_env -- the CLI is not on PATH before that.
  if globus-compute-endpoint list 2>/dev/null | grep -q "Running.*$ENDPOINT_NAME"; then
    echo "ERROR: '$ENDPOINT_NAME' is already Running -- starting again would stop it." >&2
    echo "  Use: $(basename "$0") restart" >&2
    return 1
  fi
  echo "==> Starting endpoint: $ENDPOINT_NAME"
  globus-compute-endpoint start "$ENDPOINT_NAME"
}

# ---------------------------------------------------------------------------
# start: wrap _do_start inside a tmux session
# ---------------------------------------------------------------------------

_start() {
  if [[ -z "${TMUX:-}" ]]; then
    echo "Launching tmux session '$TMUX_SESSION'..."
    # -A: attach if session exists, create otherwise; keep shell alive after endpoint exits
    exec tmux new-session -A -s "$TMUX_SESSION" \
      "bash -l \"$0\" _do_start; exec bash -l"
  fi
  # Already inside tmux. Only run in place when this *is* the endpoint session.
  # Running from some other session leaves the endpoint owned by whatever shell
  # happened to be attached, and invites a second copy started from elsewhere.
  local current
  current="$(tmux display-message -p '#S' 2>/dev/null || echo '')"
  if [[ "$current" != "$TMUX_SESSION" ]]; then
    echo "ERROR: inside tmux session '$current', not '$TMUX_SESSION'." >&2
    echo "  Detach with Ctrl-b d, then re-run from a plain shell." >&2
    return 1
  fi
  _do_start
}

# ---------------------------------------------------------------------------
# restart
# ---------------------------------------------------------------------------

_restart() {
  _load_modules
  _activate_env
  echo "==> Stopping endpoint: $ENDPOINT_NAME"
  globus-compute-endpoint stop "$ENDPOINT_NAME" 2>/dev/null || true
  rm -f "$HOME/.globus_compute/$ENDPOINT_NAME/daemon.pid"
  echo "==> Restarting..."
  globus-compute-endpoint start "$ENDPOINT_NAME"
}

# ---------------------------------------------------------------------------
# status
# ---------------------------------------------------------------------------

_status() {
  _load_modules
  _activate_env
  globus-compute-endpoint list
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

case "${1:-}" in
  configure) _configure ;;
  start)     _start ;;
  _do_start) _do_start ;;  # internal: invoked by tmux
  restart)   _restart ;;
  status)    _status ;;
  *) usage; exit 1 ;;
esac
